name: fast_api_app
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - fastapi=0.88.0
  - uvicorn=0.20.0
  - pydantic=1.10.2
  - requests=2.28.1
  - pip=22.3.1
  - pip:
      - autopep8==2.0.0